### PR TITLE
Make a copy of of libdwarf.so.0 in the old location

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Since old packages relying on libdwarf may still look for libdwarf.so.0 this PR updates the feedstock to make a copy in the old location

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
@conda-forge-admin, please rerender

**Comment by kkraus14** [comment]
@jeremy-rifkin A fix for this just got merged upstream that versions the shared library produced via CMake. Should we just bring that in via a patch for now until the next release?

**Comment by jeremy-rifkin** [comment]
Hi, thanks for pointing that out! That would be a sensible way to go, I'll try to update this PR.

**Comment by jeremy-rifkin** [comment]
Alright, hopefully ready to go now

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
Thanks @jeremy-rifkin!

**Pull request merged**
